### ISSUE TITLE
create database schema

### ISSUE THREAD

**Issue by ReflexLevel0** [ReflexLevel0/CulinaryChaosCrew#1]

**Comment by Gl1tc6** [comment]
### Database schema in devdoc???
I think that the only appropriate branch for database schema is devdoc as it is a useful infographic to understand our database and how it was designed

**BUT**

It is not part of working code, data used by said code, or in any way an active part of this project, it only serves to better understand how the DB was created and how its data is connected. For this reason, it will be placed inside devdoc branch
