### ISSUE TITLE
API - add better error handling for recipe controller

### ISSUE THREAD

**Issue by ReflexLevel0** [ReflexLevel0/CulinaryChaosCrew#70]
Currently if anything fails (for example specified user id doesn't exist when inserting recipe), the server throws 500 error instead of a useful error code with a message.
![image](https://github.com/ReflexLevel0/CulinaryChaosCrew/assets/47285986/3af741c7-d83c-487a-8d91-99f8a38d18fe)

**Comment by nix0nivis** [comment]
Done.
